blank_issues_enabled: true
contact_links:
  - name: GitHub Community Support
    url: https://github.com/eComindo/2025-github-ur-copilot-workshop/discussions
    about: Please ask and answer questions here.
